namespace GreenPaceIQ.Api;

// ---------- Input from the driver app ----------
// T = unix seconds, one point per second is ideal.
public record GpsPoint(double T, double Lat, double Lon, double SpeedKmh);

// DeviceId is optional and only used for the rewards wallet (random id generated by the app, not an account).
public record TripBatch(string TripId, string? DeviceId, bool AdvisoryActive, List<GpsPoint> Points);

// ---------- Internal ----------
public record Stop(double StartSec, double DurationSec, double Lat, double Lon);

// Raw GPS points are never stored. Only these anonymous records are kept (HLD B3).
public record StoredStop(int IntersectionId, long HourBucket, double DurationSec, bool Advised, bool Simulated);
public record StoredTrip(DateOnly Day, bool Advised, bool Simulated, int Stops, double StoppedSec, double FuelL, double Co2Kg, double DistanceM, double DurationSec);
public record Earning(DateOnly Day, int Points, double Co2SavedG);

// Signal timing and flow are SIMULATED (fixed cycle). Names and coordinates are placeholders:
// replace with OSM / dane.gov.pl data. Congestion (about 0.5 to 1.6) only shapes the simulated trips.
public record Signal(int Id, string Name, double Lat, double Lon, double RouteOffsetM,
                     int CycleSec, int GreenSec, int OffsetSec, int FlowPerHour,
                     string Code = "", double Congestion = 1.0);

public static class Signals
{
    // The first three are on the demo route (live-map and route-advice/demo). Keep their order.
    public static readonly IReadOnlyList<Signal> All = new List<Signal>
    {
        new(1, "Rondo Grzegórzeckie",    50.0574, 19.9546, 1200,  90, 40, 10,  600, "B01"),
        new(2, "Rondo Mateczny",         50.0424, 19.9735, 1530, 100, 45, 30,  900, "B02"),
        new(3, "Aleje Trzech Wieszczów", 50.0610, 19.9230, 1860,  80, 35,  0,  450, "B03"),

        // City console corridors (see CityConsole.cs). RouteOffsetM = 0: not used by live-map.
        new(4,  "Centre hub",       50.0647, 19.9450, 0, 110, 45, 20, 1200, "A17", 1.6),
        new(5,  "East avenue",      50.0650, 19.9620, 0, 100, 42, 15,  900, "A12", 1.3),
        new(6,  "West-east link",   50.0650, 19.9250, 0,  90, 45, 40,  700, "C03", 0.9),
        new(7,  "North avenue",     50.0750, 19.9300, 0,  95, 40,  5,  800, "N08", 1.0),
        new(8,  "South avenue",     50.0500, 19.9450, 0,  80, 42, 25,  600, "S05", 0.7),
        new(9,  "Diagonal east",    50.0750, 19.9680, 0, 100, 40, 55,  750, "D11", 1.1),
        new(10, "Diagonal west",    50.0520, 19.9150, 0,  85, 40, 10,  500, "D02", 0.6),

        // Intersections used by the team's Live Traffic map (ids 11-17, same coordinates as their mock).
        new(11, "Rondo Mogilskie",               50.0660, 19.9594, 0, 120, 45, 20, 1500, "MOG", 1.7),
        new(12, "Rondo Grzegórzeckie",           50.0576, 19.9591, 0, 110, 42, 35, 1400, "GRZ", 1.6),
        new(13, "Rondo Grunwaldzkie",            50.0489, 19.9320, 0, 100, 42, 10, 1000, "GRU", 1.2),
        new(14, "Mickiewicza × Czarnowiejska",   50.0643, 19.9243, 0, 100, 40, 50, 1100, "MCZ", 1.5),
        new(15, "Aleja Krasińskiego",            50.0577, 19.9262, 0,  95, 40,  5,  900, "KRA", 1.3),
        new(16, "Dietla × Starowiślna",          50.0559, 19.9451, 0,  90, 42, 25,  800, "DST", 1.1),
        new(17, "Old Town / Planty",             50.0617, 19.9373, 0,  70, 40, 15,  300, "OLD", 0.5),
    };

    public static Signal? Match(double lat, double lon)
    {
        Signal? best = null;
        double bestDist = Assumptions.MatchRadiusM;
        foreach (var s in All)
        {
            var d = Geo.DistanceM(lat, lon, s.Lat, s.Lon);
            if (d <= bestDist) { best = s; bestDist = d; }
        }
        return best;
    }
}
